### ISSUE TITLE
rip-the-zip.py is corrupt or not using standard encoding (UTF-8??)

### ISSUE THREAD

**Issue by Cyber5imon** [John-kener/RIP-THE-ZIP#1]
python3 rip-the-zip.py

File "rip-the-zip.py", line 4
SyntaxError: Non-UTF-8 code starting with '\x9f' in file rip-the-zip.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Also unable to view file in GitHub, it thinks it is a binary file....

**Comment by John-kener** [comment]
Yes Brother
I have compiled that file into bytes.
The reason for this issue may be you are using a previous version of python ,due to a latest update (version 3.10) available for python.
So I recommend you to update your python version to latest version,and i think program will work correctly after that.

Kali Linux : `sudo apt update`

Termux :  `pkg update && pkg upgrade`

Try this way & comment your result...
